name: Pull request

on: 
  workflow_dispatch:
  pull_request:
  workflow_call:

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6'
      
      - name: Build
        working-directory: ./Solution
        run: dotnet build

      - name: Test
        working-directory: ./Solution
        run: dotnet test
